### ISSUE TITLE
Manage own pictures

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [SimonPrimetzhofer/mms#10]
Users should be able to manage their own pictures and 
* create
* update
* delete

List-view with own pictures in profile page

**Comment by JakobRumpelsberger** [comment]
I think the update functionality is not necessary in this case

**Comment by SimonPrimetzhofer** [comment]
> I think the update functionality is not necessary in this case

it should be possible to update the title, tag, ...

**Comment by JakobRumpelsberger** [comment]
ok

**Comment by SimonPrimetzhofer** [comment]
@JakobRumpelsberger im menü hätte es scho ein eintrag gegeben, der den die pictures mit dem filter 'my' aufruft. möglicherweise wäre es so einfacher.
