### ISSUE TITLE
Admin-Page

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [SimonPrimetzhofer/mms#4]
Create Admin-Page for managing portal content
* list-view with all pictures
* view pictures and metadata
* deleting pictures should be possible
* updating metadata should be possible (remove inappropriate content)
* view requests from users and mark them done

**Comment by JakobRumpelsberger** [comment]
i glaub diese funktion ist nicht wirklich nötig, der user hat sowieso die möglichkeit das bild selbst hochzuladen ohne request (issue #10). wir sollten uns eher auf das editieren vom bild konzentrieren anstatt reine funktionalitäten des portals

**Comment by SimonPrimetzhofer** [comment]
es macht dahingehend sinn, dass alle auf ihre 20 stunden kommen.
